services:
  mcp-server-chart:
    build:
      context: .          # Dockerfile dir
      dockerfile: Dockerfile
    image: mcp-server-chart:stable
    container_name: mcp-server-chart-1
    # environment:
    #   - VIS_REQUEST_SERVER=http://127.0.0.1:3000/render  # Notice: You can use AntV's project GPT-Vis-SSR to deploy an HTTP service in a private environment, and then pass the URL address through env VIS_REQUEST_SERVER.
    command: ["node", "build/index.js", "--transport", "sse", "--port", "1122", "--host", "0.0.0.0"]
    ports:
      - "1122:1122"
# networks:
#     - internal
