name: Publish to MCP Registry

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'   # 纯数字版本号（如 1.2.3）

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # OIDC 登录需要

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Update server.json version
        run: sed -i "s/{{VERSION}}/$GITHUB_REF_NAME/g" server.json

      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/download/v1.0.0/mcp-publisher_1.0.0_linux_amd64.tar.gz" \
          | tar xz mcp-publisher

      - name: Login & Publish to MCP Registry
        run: |
          ./mcp-publisher login github-oidc
          ./mcp-publisher publish
